version: '3'
services:
    postgres:
        image: 'postgres:latest'
        stdin_open: true
        restart: always
        environment:
          POSTGRES_PASSWORD: postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '3050:80'

    api:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        ## to reflect changes made on disk into container
        volumes:  
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGHOST=postgres
            - PGUSER=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
            - PGDATABASE=postgres
    client:
        stdin_open: true # docker run -i
      #  tty: true        # docker run -t
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app    